version: '2'
services:
  # Only one for the whole cluster
  consul:
    command: agent -server -dev -ui -node=server -client=0.0.0.0
    image: consul:1.9.7
    container_name: 'server'
    ports:
      - "8500:8500"
    environment:
      SERVICE_53_IGNORE: 'yes'
      SERVICE_8300_IGNORE: 'yes'
      SERVICE_8301_IGNORE: 'yes'
      SERVICE_8302_IGNORE: 'yes'
      SERVICE_8400_IGNORE: 'yes'
      SERVICE_8500_NAME: 'consul-service-on-server'

  # Exactly one per physical node
  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    container_name: 'registrator'
    links:
      - "consul"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  web:
    image: hashicorp/counting-service:0.0.2
    ports:
      - "9001"
    environment:
      SERVICE_NAME: 'counting-service'
      SERVICE_CHECK_HTTP: '/'
      SERVICE_CHECK_INTERVAL: '5s'


  template:
    image: hashicorp/consul-template:alpine
    command: "-config /templates/consul-tmplate.hcl"
    volumes:
      - "./templates/:/templates"
    links:
      - "consul"
    depends_on:
      - consul
